In [22]:
import pandas as pd
csv_directory = "..\..\PROMICE-AWS-toolbox\out\L4\CEN1_L4.csv"
#df = pd.read_csv(csv_directory)
data_directory2 = "../data/new_promice/all_promice_data.parquet.gzip"
df = pd.read_parquet(data_directory2)

In [7]:
#display(df)
display(df['station_name'].unique())
print(list(df.columns))

array(['CEN1', 'CEN2', 'CP1', 'DY2', 'EGP', 'HUM', 'JAR', 'JAR_O',
       'KAN_B', 'KAN_L', 'KAN_M', 'KAN_U', 'KPC_Lv3', 'KPC_L', 'KPC_Uv3',
       'KPC_U', 'LYN_L', 'LYN_T', 'MIT', 'NAE', 'NAU', 'NEM', 'NSE',
       'NUK_K', 'NUK_L', 'NUK_N', 'NUK_Uv3', 'NUK_U', 'QAS_A', 'QAS_Lv3',
       'QAS_L', 'QAS_M', 'QAS_Uv3', 'QAS_U', 'Roof_GEUS', 'Roof_PROMICE',
       'SCO_L', 'SCO_U', 'SDL', 'SDM', 'SWC', 'SWC_O', 'TAS_A', 'TAS_L',
       'TAS_U', 'THU_L2', 'THU_L', 'THU_U2', 'THU_U', 'TUN', 'UPE_L',
       'UPE_U', 'UWN', 'WEG_B', 'ZAK_L', 'ZAK_Uv3', 'ZAK_U'], dtype=object)

['station_name', 'time', 'p_u', 't_u', 'rh_u', 'rh_u_cor', 'qh_u', 'wspd_u', 'wdir_u', 'dsr', 'dsr_cor', 'usr', 'usr_cor', 'albedo', 'dlr', 'ulr', 'cc', 't_surf', 'dlhf_u', 'dshf_u', 'z_boom_u', 'z_stake', 'z_pt', 'z_pt_cor', 'precip_u', 'precip_u_cor', 't_i_1', 't_i_2', 't_i_3', 't_i_4', 't_i_5', 't_i_6', 't_i_7', 't_i_8', 'tilt_x', 'tilt_y', 'rot', 'gps_lat', 'gps_lon', 'gps_alt', 'gps_time', 'gps_geoid', 'gps_geounit', 'gps_hdop', 'gps_numsat', 'gps_q', 'batt_v', 'batt_v_ini', 'batt_v_ss', 'fan_dc_u', 'freq_vw', 't_log', 't_rad', 'msg_lat', 'msg_lon', 'z_surf_1', 'z_surf_2', 'z_surf_1_adj_flag', 'z_surf_2_adj_flag', 'z_surf_combined', 'depth_t_i_1', 'depth_t_i_2', 'depth_t_i_3', 'depth_t_i_4', 'depth_t_i_5', 'depth_t_i_6', 'depth_t_i_7', 'depth_t_i_8', 't_i_10m', 'p_l', 't_l', 'rh_l', 'rh_l_cor', 'qh_l', 'wspd_l', 'wdir_l', 'dlhf_l', 'dshf_l', 'z_boom_l', 'precip_l', 'precip_l_cor', 't_i_9', 't_i_10', 't_i_11', 'fan_dc_l', 'depth_t_i_9', 'depth_t_i_10', 'depth_t_i_11', 'z_pt_cor_adj_flag', 'z_pt_cor_adj', 'z_surf_1_adj', 'z_surf_2_adj', 'AirPressure(hPa)', 'AirTemperature(C)', 'RelativeHumidity(%)', 'RelativeHumidity_cor(%)', 'SpecificHumidity(g/kg)', 'WindSpeed(m/s)', 'WindDirection(d)', 'ShortwaveRadiationDown(W/m2)', 'ShortwaveRadiationDown_Cor(W/m2)', 'ShortwaveRadiationUp(W/m2)', 'ShortwaveRadiationUp_Cor(W/m2)', 'Albedo', 'LongwaveRadiationDown(W/m2)', 'LongwaveRadiationUp(W/m2)', 'CloudCover', 'SurfaceTemperature(C)', 'LatentHeatFlux(W/m2)', 'SensibleHeatFlux(W/m2)', 'HeightSensorBoom(m)', 'HeightStakes(m)', 'DepthPressureTransducer(m)', 'DepthPressureTransducer_Cor(m)', 'Precipitation', 'Precipitation_Cor', 'IceTemperature1(C)', 'IceTemperature2(C)', 'IceTemperature3(C)', 'IceTemperature4(C)', 'IceTemperature5(C)', 'IceTemperature6(C)', 'IceTemperature7(C)', 'IceTemperature8(C)', 'TiltToEast(d)', 'TiltToNorth(d)', 'Heading', 'LatitudeGPS(degN)', 'LongitudeGPS(degW)', 'ElevationGPS(m)', 'TimeGPS(hhmmssUTC)', 'HorDilOfPrecGPS', 'SnowHeight(m)', 'SurfaceHeight(m)', 'DepthPressureTransducer_Cor_adj(m)', 'SnowHeight_adj(m)', 'SurfaceHeight_adj(m)', 'SurfaceHeight1_adj(m)', 'SurfaceHeight2_adj(m)', 'SurfaceHeight_summary(m)', 'depth_1', 'depth_2', 'depth_3', 'depth_4', 'depth_5', 'depth_6', 'depth_7', 'depth_8', 'IceTemperature10m(C)']

In [12]:
#null_columns = df.columns[df.isnull().all()]
flag_columns = df.filter(regex="flag$").columns
print("null columns:\n", null_columns.sort_values())
print("flag_columns:\n", flag_columns)

null columns:
 Index(['DepthPressureTransducer(m)', 'DepthPressureTransducer_Cor(m)',
       'DepthPressureTransducer_Cor_adj(m)', 'ElevationGPS(m)',
       'HorDilOfPrecGPS', 'IceTemperature10m(C)', 'IceTemperature7(C)',
       'IceTemperature8(C)', 'LatitudeGPS(degN)', 'LongitudeGPS(degW)',
       'TimeGPS(hhmmssUTC)', 'batt_v_ini', 'freq_vw', 'gps_geounit'],
      dtype='object')
flag_columns:
 Index(['z_surf_1_adj_flag', 'z_surf_2_adj_flag', 'z_pt_cor_adj_flag'], dtype='object')

In [32]:
import pandas as pd
import numpy as np

# Load your data into a pandas DataFrame (replace "data.csv" with the name of your file)


# Define the date column that you want to group by (replace "date_column" with the name of your column)
min_values_per_day = 20

# Group the data by weather station and date
grouped = df.groupby(['stid','date'])

# Calculate the number of non-NaN values for each variable within each group
non_nan_counts = grouped.apply(lambda x: x.notnull().sum())

# Filter out groups where any variable has less than min_values_per_day non-NaN values
filtered_groups = grouped.filter(lambda x: (x.notnull().sum() >= min_values_per_day).all())

# Get a list of the columns to average (i.e. all columns except for the date column)
columns_to_average = df.select_dtypes(exclude=['object']).columns

# Group the data by date and calculate the mean for each column
# Calculate the mean for each variable within each group
means = filtered_groups.groupby(['stid','date'])[columns_to_average].mean()

# Display the results
print(means)

                    index  stid  Datetime  p_u  t_u  rh_u  rh_u_cor  qh_u  \
stid    date
CEN1    2017-05-23      0     0         0   14   14    14        14    14
        2017-05-24      0     0         0   24   24    24        24    24
        2017-05-25      0     0         0   24   24    24        24    24
        2017-05-26      0     0         0   24   24    24        24    24
        2017-05-27      0     0         0   24   24    24        24    24
...                   ...   ...       ...  ...  ...   ...       ...   ...
ZAK_Uv3 2022-12-21      0     0         0    0    0     0         0     0
        2022-12-22      0     0         0    0    0     0         0     0
        2022-12-23      0     0         0    2    2     2         2     4
        2022-12-24      0     0         0    1    1     1         1     2
        2022-12-25      0     0         0    2    2     2         2     3

                    wspd_u  wdir_u  ...  depth_8  IceTemperature10m(C)  year  \
stid    date                        ...
CEN1    2017-05-23      13      13  ...       14                    14     0
        2017-05-24      24      24  ...       24                    24     0
        2017-05-25      24      24  ...       24                    24     0
        2017-05-26      24      24  ...       24                    24     0
        2017-05-27      24      24  ...       24                    24     0
...                    ...     ...  ...      ...                   ...   ...
ZAK_Uv3 2022-12-21       0       0  ...       24                    24     0
        2022-12-22       0       0  ...       24                    24     0
        2022-12-23       2       2  ...       24                    24     0
        2022-12-24       1       1  ...       24                    24     0
        2022-12-25       2       2  ...       16                    16     0

                    month  season  DayOfYear  DayOfCentury  day  hour  date
stid    date
CEN1    2017-05-23      0       0          0             0    0     0     0
        2017-05-24      0       0          0             0    0     0     0
        2017-05-25      0       0          0             0    0     0     0
        2017-05-26      0       0          0             0    0     0     0
        2017-05-27      0       0          0             0    0     0     0
...                   ...     ...        ...           ...  ...   ...   ...
ZAK_Uv3 2022-12-21      0       0          0             0    0     0     0
        2022-12-22      0       0          0             0    0     0     0
        2022-12-23      0       0          0             0    0     0     0
        2022-12-24      0       0          0             0    0     0     0
        2022-12-25      0       0          0             0    0     0     0

[248036 rows x 158 columns]